---
apiVersion: v1
kind: Pod
metadata:
  name: testbox
spec:
  containers:
  - name: dnsutils
    image: tutum/dnsutils
    command:
      - /bin/bash
      - -c
      - while true; do sleep 1; done
  nodeSelector:
    nodeTag: newlyAdded
