apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: testbox
  name: testbox
  namespace: kpipe
spec:
  progressDeadlineSeconds: 600
  replicas: 8 
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: testbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: testbox
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - while true; do sleep 1; done
        image: tutum/dnsutils
        imagePullPolicy: IfNotPresent
        name: testbox
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        nodeTags: newlyAdded
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
