apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-authtest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-authtest
  template:
    metadata:
      labels:
        app: helloworld-authtest
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo:latest
        ports:
        - name: nodejs-port
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-authtest-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-authtest
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-authtest-rules
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri" 
spec:
  rules:
  - host: authtest.cdnlab.comcast.net
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-authtest-svc
          servicePort: 80
