---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-endpoints
  namespace: trickster-test
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: clickhouse-endpoints
  namespace: trickster-test
subsets:
  - addresses:
      - ip: 96.113.151.79
      - ip: 96.113.151.78
      - ip: 96.113.151.80
    ports:
      - port: 8123
