apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: endpoint-tester
  name: endpoint-tester
  namespace: trickster-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: endpoint-tester
  template:
    metadata:
      annotations:
      labels:
        app: endpoint-tester
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - while true; do sleep 1; done
        image: centos:7
        imagePullPolicy: IfNotPresent
        name: shell
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
