apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: pv-proxy
  name: kpipe-pv-proxy
  namespace: kpipe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pv-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: pv-proxy
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - while true; do sleep 1; done
        image: centos:7
        imagePullPolicy: IfNotPresent
        name: shell
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kpipe/jobs
          name: my-kpipe-pvc
        - mountPath: /kpipe/certs
          name: kpipe-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: my-kpipe-pvc
        persistentVolumeClaim:
          claimName: kpipe-pvc
      - name: kpipe-certs
        persistentVolumeClaim:
          claimName: kpipe-certs
