apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kpipe-pv-proxy
  name: kpipe-pv-proxy
  namespace: kpipe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kpipe-pv-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: kpipe-pv-proxy
    spec:
      nodeSelector:
        nodeKey: targeted
      containers:
      - command:
        - bin/bash
        - -c
        - while true; do sleep 1; done
        image: centos:7
        imagePullPolicy: IfNotPresent
        name: shell
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kpipe/certs
          name: my-kpipe-pvc
          subPath: kpipe/certs
        - mountPath: /kpipe/jobs
          name: my-kpipe-pvc
          subPath: kpipe/jobs
        - mountPath: /longhorn
          name: my-longhorn-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: my-kpipe-pvc
        persistentVolumeClaim:
          claimName: maple-config
      - name: my-longhorn-pvc
        persistentVolumeClaim:
          claimName: longhorn-fio-test-pvc
