apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: debug-cli
  name: debug-cli 
  namespace: maple-develop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: debug-cli
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: debug-cli
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - while true; do sleep 1; done
        image: hub.comcast.net/ipcdn/magma:debug-cli
        imagePullPolicy: IfNotPresent
        name: shell
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
