apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: nfs-proxy
  name: nfs-proxy
  namespace: maple-airflow-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nfs-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: nfs-proxy
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - mkdir -p /home/airflow/airflow && while true; do sleep 1; done
        image: centos:7
        env:
          - name: AIRFLOW_HOME
            value: "Test out"
        volumeMounts:
          - mountPath: /home/airflow/airflow/airflow.cfg
            name: airflowconfigs
            subPath: airflow.cfg
          - mountPath: /home/airflow/airflow/dags
            name: airflowdags
        imagePullPolicy: IfNotPresent
        name: shell
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: airflowconfigs
        configMap:
          name: airflow-config
      - name: airflowdags
        persistentVolumeClaim:
          claimName: airflow-dags
